package presentacion;

import cubuscarmascotaideal.dtos.MascotaResultadoDTO;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;

/**
 * Panel de tarjeta para mostrar mascotas ideales con su puntaje de
 * compatibilidad
 * 
 * @author Josel
 */
public class PetCardIdealPanel extends javax.swing.JPanel {

    private MascotaResultadoDTO mascotaResultado;

    /**
     * Creates new form PetCardIdealPanel
     */
    public PetCardIdealPanel() {
        initComponents();
    }

    /**
     * Establece la mascota resultado y actualiza la vista
     */
    public void setMascotaResultado(MascotaResultadoDTO mascotaResultado) {
        this.mascotaResultado = mascotaResultado;

        if (mascotaResultado != null) {
            // Establecer nombre
            lbNombreMascota.setText(mascotaResultado.getNombre());

            // Establecer imagen
            setImagenMascota(mascotaResultado.getUrlImagen());

            // Mostrar puntaje de compatibilidad
            lbCompatibilidad.setText(
                    "Compatibilidad: " + String.format("%.0f", mascotaResultado.getPorcentajeCompatibilidad()) + "%");
        }
    }

    /**
     * Establece la imagen de la mascota
     */
    private void setImagenMascota(String urlImagen) {
        try {
            if (urlImagen != null && !urlImagen.isEmpty()) {
                ImageIcon icon = null;

                // Verificar si es una URL de internet (HTTP/HTTPS)
                if (urlImagen.startsWith("http://") || urlImagen.startsWith("https://")) {
                    try {
                        java.net.URL url = new java.net.URL(urlImagen);
                        icon = new ImageIcon(url);
                    } catch (Exception e) {
                        System.err.println("Error cargando imagen desde URL: " + urlImagen);
                        e.printStackTrace();
                    }
                }
                // Intentar cargar desde resources (ruta relativa que empieza con /)
                else if (urlImagen.startsWith("/")) {
                    java.net.URL imgURL = getClass().getResource(urlImagen);
                    if (imgURL != null) {
                        icon = new ImageIcon(imgURL);
                    } else {
                        System.err.println("No se encontró la imagen en resources: " + urlImagen);
                    }
                }
                // Es una ruta absoluta local
                else {
                    File imgFile = new File(urlImagen);
                    if (imgFile.exists()) {
                        icon = new ImageIcon(urlImagen);
                    } else {
                        System.err.println("No se encontró la imagen en disco: " + urlImagen);
                    }
                }

                // Si se cargó la imagen, redimensionarla y mostrarla
                if (icon != null && icon.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE) {
                    Image img = icon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH);
                    lbImagenMascota.setIcon(new ImageIcon(img));
                    lbImagenMascota.setText("");
                } else {
                    lbImagenMascota.setText("Sin imagen");
                }
            } else {
                lbImagenMascota.setText("Sin imagen");
            }
        } catch (Exception e) {
            lbImagenMascota.setText("Error al cargar");
            System.err.println("Error cargando imagen: " + urlImagen);
            e.printStackTrace();
        }
    }

    /**
     * Obtiene la mascota resultado
     */
    public MascotaResultadoDTO getMascotaResultado() {
        return mascotaResultado;
    }

    /**
     * Agrega un listener al botón de adoptar
     */
    public void agregarListenerAdoptar(ActionListener listener) {
        btnAdoptar.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbImagenMascota = new javax.swing.JLabel();
        btnAdoptar = new javax.swing.JButton();
        lbNombreMascota = new javax.swing.JLabel();
        lbCompatibilidad = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(235, 229, 220));

        lbImagenMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagenMascota.setText("image");

        btnAdoptar.setBackground(new java.awt.Color(80, 172, 80));
        btnAdoptar.setText("ADOPTAR");
        btnAdoptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptarActionPerformed(evt);
            }
        });

        lbNombreMascota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombreMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreMascota.setText("nombreMascota");

        lbCompatibilidad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCompatibilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCompatibilidad.setText("Compatibilidad: 0%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(lbImagenMascota, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(lbNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(lbCompatibilidad, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(btnAdoptar, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(62, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addComponent(lbImagenMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbNombreMascota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCompatibilidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdoptar, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdoptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdoptarActionPerformed
        // El listener se agrega desde afuera
    }// GEN-LAST:event_btnAdoptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdoptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCompatibilidad;
    private javax.swing.JLabel lbImagenMascota;
    private javax.swing.JLabel lbNombreMascota;
    // End of variables declaration//GEN-END:variables
}
