/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion.gestioncatalogo;

/**
 *
 * @author angel
 */
import javax.swing.JOptionPane;

public class DarBajaMascota extends javax.swing.JPanel {

    private PanelPrincipalGestionCatalogo panelPrincipal;
    private gestion.catalogo.dtos.CatalogoDTO mascotaActual;

    /**
     * Creates new form ConfirmacionEliminarDialog
     */
    public DarBajaMascota() {
        initComponents();
    }

    public void setPanelPrincipal(PanelPrincipalGestionCatalogo panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }

    public void setDatosMascota(gestion.catalogo.dtos.CatalogoDTO mascota) {
        if (mascota == null) {
            return;
        }
        this.mascotaActual = mascota;
        // Cargar datos de la mascota en los campos
        tfNombre.setText(mascota.getNombre() != null ? mascota.getNombre() : "");
        tfEspecie.setText(mascota.getEspecie() != null ? mascota.getEspecie() : "");
        tfRaza.setText(mascota.getRaza() != null ? mascota.getRaza() : "");
        tfColor.setText(mascota.getColor() != null ? mascota.getColor() : "");
        tfEdad.setText(String.valueOf(mascota.getEdad()));
        tfPeso.setText(String.valueOf(mascota.getPeso()));
        tfCondicion.setText(mascota.getEstadoSalud() != null ? mascota.getEstadoSalud() : "");

        // Cargar imagen
        if (mascota.getUrlImagen() != null && !mascota.getUrlImagen().isEmpty()) {
            cargarImagen(mascota.getUrlImagen());
        } else {
            lbl_Img.setIcon(null);
            lbl_Img.setText("Sin Imagen");
        }
    }

    private void cargarImagen(String urlImagen) {
        if (urlImagen == null || urlImagen.isEmpty()) {
            lbl_Img.setIcon(null);
            lbl_Img.setText("Sin imagen");
            return;
        }
        try {
            // Normalizar la ruta: quitar "/" inicial si existe
            String rutaRecurso = urlImagen.startsWith("/") ? urlImagen.substring(1) : urlImagen;

            // Intentar cargar desde recursos
            java.net.URL imageUrl = getClass().getClassLoader().getResource(rutaRecurso);
            if (imageUrl != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imageUrl);
                java.awt.Image img = icon.getImage().getScaledInstance(
                        lbl_Img.getWidth() > 0 ? lbl_Img.getWidth() : 200,
                        lbl_Img.getHeight() > 0 ? lbl_Img.getHeight() : 200,
                        java.awt.Image.SCALE_SMOOTH);
                lbl_Img.setIcon(new javax.swing.ImageIcon(img));
                lbl_Img.setText("");
            } else {
                // Intentar cargar como archivo absoluto
                java.io.File file = new java.io.File(urlImagen);
                if (file.exists()) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(urlImagen);
                    java.awt.Image img = icon.getImage().getScaledInstance(
                            lbl_Img.getWidth() > 0 ? lbl_Img.getWidth() : 200,
                            lbl_Img.getHeight() > 0 ? lbl_Img.getHeight() : 200,
                            java.awt.Image.SCALE_SMOOTH);
                    lbl_Img.setIcon(new javax.swing.ImageIcon(img));
                    lbl_Img.setText("");
                } else {
                    lbl_Img.setIcon(null);
                    lbl_Img.setText("Imagen no encontrada");
                }
            }
        } catch (Exception e) {
            System.err.println("Error al cargar imagen: " + e.getMessage());
            lbl_Img.setIcon(null);
            lbl_Img.setText("Error al cargar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lbl_Img = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfRaza = new javax.swing.JTextField();
        tfCondicion = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        tfEdad = new javax.swing.JTextField();
        tfColor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfEspecie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 213, 195));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(204, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSiguiente.setText("DAR DE BAJA");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lbl_Img.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Seguro que desea dar de Baja a esta mascota?");

        tfRaza.setBackground(new java.awt.Color(204, 204, 204));

        tfCondicion.setBackground(new java.awt.Color(204, 204, 204));

        tfPeso.setBackground(new java.awt.Color(204, 204, 204));

        tfEdad.setBackground(new java.awt.Color(204, 204, 204));

        tfColor.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Condición");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Peso");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Edad");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Color");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Raza");

        tfEspecie.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Especie");

        tfNombre.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("MOTIVO DE BAJA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(260, 260, 260)
                                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 187,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(69, 69, 69)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(tfNombre,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        375,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                        jPanel2Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        tfEdad,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        139,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(25,
                                                                                                                        25,
                                                                                                                        25)
                                                                                                                .addGroup(
                                                                                                                        jPanel2Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                        false)
                                                                                                                                .addComponent(
                                                                                                                                        jLabel13)
                                                                                                                                .addComponent(
                                                                                                                                        tfColor)
                                                                                                                                .addComponent(
                                                                                                                                        jLabel9)
                                                                                                                                .addComponent(
                                                                                                                                        tfCondicion,
                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                        211,
                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                        .addComponent(jLabel4))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(jLabel12)
                                                                                        .addComponent(tfRaza)
                                                                                        .addComponent(jLabel14)
                                                                                        .addComponent(tfEspecie,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                158,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(tfPeso,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                139,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel6))
                                                                .addGap(18, 18, 18))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addComponent(jLabel8)
                                                                        .addGap(145, 145, 145)))
                                                .addComponent(lbl_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 315,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 622,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(tfNombre,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(tfEspecie,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(9, 9, 9)
                                                                                                .addComponent(jLabel6)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(tfEdad,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(
                                                                                                        jLabel14))))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel13)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(tfColor,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(tfRaza,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfPeso,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfCondicion,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57,
                                                        Short.MAX_VALUE)
                                                .addComponent(jLabel8))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lbl_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 244,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)));

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "¿Desea cancelar la operación?", "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            if (panelPrincipal != null) {
                panelPrincipal.mostrarCatalogo();
            }
        }
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
        if (mascotaActual == null) {
            JOptionPane.showMessageDialog(this, "No hay mascota seleccionada.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String motivo = textArea1.getText().trim();
        if (motivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un motivo para la baja.", "Campo Requerido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int resp = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea dar de baja a " + mascotaActual.getNombre()
                        + "?\nEsta acción cambiará su estado a NO DISPONIBLE.",
                "Confirmar Baja Definitiva",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (resp == JOptionPane.YES_OPTION) {
            if (panelPrincipal != null) {
                panelPrincipal.confirmarBajaMascota(mascotaActual, motivo);
            }
        }
    }// GEN-LAST:event_btnSiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Img;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfCondicion;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfEspecie;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfRaza;
    // End of variables declaration//GEN-END:variables
}
