/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.gestioncatalogo;

import gestion.catalogo.control.ControlPresentacion;
import gestion.catalogo.dtos.CatalogoDTO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Panel para gestión del catálogo de mascotas
 */
public class GestionCatalogoPanel extends javax.swing.JPanel {

    private ControlPresentacion controlPresentacion;
    private PanelPrincipalGestionCatalogo panelPrincipal; // Referencia al panel principal para navegación

    /**
     * Creates new form GestionCatalogoPanel
     */
    public GestionCatalogoPanel() {
        initComponents();

        // Inicializar control
        this.controlPresentacion = new ControlPresentacion();

        // Cargar catálogo
        cargarCatalogo();

        // Configurar scroll
        JScrollPaneCatalogo.getVerticalScrollBar().setUnitIncrement(16);
        JScrollPaneCatalogo.getVerticalScrollBar().setBlockIncrement(100);
    }

    /**
     * Configura el listener del botón agregar mascota
     */
    public void configurarBotonAgregar(Runnable accion) {
        btn_agregarMascota.addActionListener(e -> accion.run());
    }

    /**
     * Setea la referencia al panel prin cipal para navegación
     */
    public void setPanelPrincipal(PanelPrincipalGestionCatalogo panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }

    /**
     * Carga el catálogo de mascotas
     */
    public void cargarCatalogo() {
        try {
            // Limpiar panel
            JPaneCatalogo.removeAll();

            // Obtener mascotas
            List<CatalogoDTO> mascotas = controlPresentacion.obtenerCatalogo();

            if (mascotas == null || mascotas.isEmpty()) {
                System.out.println("No hay mascotas en el catálogo");
                JPaneCatalogo.revalidate();
                JPaneCatalogo.repaint();
                return;
            }

            System.out.println("Cargando catálogo con " + mascotas.size() + " mascotas...");

            // Crear PetCard por cada mascota
            for (CatalogoDTO mascota : mascotas) {
                System.out.println("Creando card para: " + mascota.getNombre()
                        + " (ID: " + mascota.getId() + ", URL: " + mascota.getUrlImagen()
                        + ")");

                PetCardPanel card = new PetCardPanel();

                //  Usar método simplificado para setear todos los datos
                card.setDatosMascota(mascota);

                // Listener para ver detalles
                card.agregarListenerDetalle(e -> {
                    mostrarDetallesMascota(mascota.getId());
                });

                // Listener para editar
                card.agregarListenerEditar(e -> {
                    if (panelPrincipal != null) {
                        panelPrincipal.editarMascota(mascota);
                    }
                });

                // Listener para eliminar
                card.agregarListenerEliminar(e -> {
                    if (panelPrincipal != null) {
                        panelPrincipal.eliminarMascota(mascota);
                    }
                });

                JPaneCatalogo.add(card);
            }

            // Refrescar UI
            JPaneCatalogo.revalidate();
            JPaneCatalogo.repaint();

            System.out.println("Catálogo cargado exitosamente: " + mascotas.size() + " mascotas");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al cargar catálogo: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Muestra los detalles de una mascota navegando al panel de detalles
     */
    private void mostrarDetallesMascota(String idMascota) {
        if (panelPrincipal != null) {
            // Delegar al panel principal que maneja la navegación
            panelPrincipal.mostrarDetallesMascota(idMascota);
        } else {
            System.err.println("Panel principal no configurado");
            JOptionPane.showMessageDialog(this,
                    "Error de configuración: no se puede navegar a detalles",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Recarga el catálogo
     */
    public void recargarCatalogo() {
        cargarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JScrollPaneCatalogo = new javax.swing.JScrollPane();
        JPaneCatalogo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        perro6 = new javax.swing.JLabel();
        btn_infoMascota2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        perro5 = new javax.swing.JLabel();
        btn_infoMascota1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        perro3 = new javax.swing.JLabel();
        btn_infoMascota = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_agregarMascota = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(219, 213, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JScrollPaneCatalogo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        JPaneCatalogo.setBackground(new java.awt.Color(235, 229, 220));
        JPaneCatalogo.setLayout(new java.awt.GridLayout(0, 3, 15, 15));

        btn_infoMascota2.setText("VER DETALLES");
        btn_infoMascota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoMascota2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Cacao");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(perro6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_infoMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(107, 107, 107))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(perro6)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(btn_infoMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        JPaneCatalogo.add(jPanel3);

        btn_infoMascota1.setText("VER DETALLES");
        btn_infoMascota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoMascota1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Pinto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_infoMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perro5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(perro5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(btn_infoMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        JPaneCatalogo.add(jPanel2);

        btn_infoMascota.setText("VER DETALLES");
        btn_infoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoMascotaActionPerformed(evt);
            }
        });

        jLabel3.setText("Rufus");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(perro3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btn_infoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(perro3)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(btn_infoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        JPaneCatalogo.add(jPanel4);

        JScrollPaneCatalogo.setViewportView(JPaneCatalogo);

        jPanel1.add(JScrollPaneCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1400, 420));

        btn_agregarMascota.setText("Agregar Nueva Mascota");
        jPanel1.add(btn_agregarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 540, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1428, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infoMascota2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_infoMascota2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_infoMascota2ActionPerformed

    private void btn_infoMascota1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_infoMascota1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_infoMascota1ActionPerformed

    private void btn_infoMascotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_infoMascotaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_infoMascotaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPaneCatalogo;
    private javax.swing.JScrollPane JScrollPaneCatalogo;
    private javax.swing.JButton btn_agregarMascota;
    private javax.swing.JButton btn_infoMascota;
    private javax.swing.JButton btn_infoMascota1;
    private javax.swing.JButton btn_infoMascota2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel perro3;
    private javax.swing.JLabel perro5;
    private javax.swing.JLabel perro6;
    // End of variables declaration//GEN-END:variables
}
