/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

/**
 *
 * @author angel
 */
/**
 * Panel para mostrar el expediente médico de una mascota.
 * 
 * @author angel
 */
public class ExpedienteMedico extends javax.swing.JPanel {

    /**
     * Creates new form ExpedienteMedico
     */
    public ExpedienteMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        cbAdoptadoPreviamente = new javax.swing.JCheckBox();
        tfCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbAdoptadoPreviamente1 = new javax.swing.JCheckBox();
        cbAdoptadoPreviamente2 = new javax.swing.JCheckBox();
        cbAdoptadoPreviamente4 = new javax.swing.JCheckBox();
        cbAdoptadoPreviamente3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        cbAdoptadoPreviamente5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        tfCorreo1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btn_regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 213, 195));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        cbAdoptadoPreviamente.setForeground(new java.awt.Color(0, 0, 0));
        cbAdoptadoPreviamente.setText("Rabia");
        cbAdoptadoPreviamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdoptadoPreviamenteActionPerformed(evt);
            }
        });

        tfCorreo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Alergias Detectadas");

        tfNombre.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Condición");

        cbAdoptadoPreviamente1.setForeground(new java.awt.Color(0, 0, 0));
        cbAdoptadoPreviamente1.setText("Desparasitación Externa");
        cbAdoptadoPreviamente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdoptadoPreviamente1ActionPerformed(evt);
            }
        });

        cbAdoptadoPreviamente2.setForeground(new java.awt.Color(0, 0, 0));
        cbAdoptadoPreviamente2.setText("Bordetella");
        cbAdoptadoPreviamente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdoptadoPreviamente2ActionPerformed(evt);
            }
        });

        cbAdoptadoPreviamente4.setForeground(new java.awt.Color(0, 0, 0));
        cbAdoptadoPreviamente4.setText("Desparasitación Interna");
        cbAdoptadoPreviamente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdoptadoPreviamente4ActionPerformed(evt);
            }
        });

        cbAdoptadoPreviamente3.setForeground(new java.awt.Color(0, 0, 0));
        cbAdoptadoPreviamente3.setText("Múltiple/Quíntuple");
        cbAdoptadoPreviamente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdoptadoPreviamente3ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Vacunas");

        cbAdoptadoPreviamente5.setForeground(new java.awt.Color(0, 0, 0));
        cbAdoptadoPreviamente5.setText("Esterilizado");
        cbAdoptadoPreviamente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdoptadoPreviamente5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Condiciones Especiales");

        tfCorreo1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nivel de Energía / Comportamiento");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cbAdoptadoPreviamente,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbAdoptadoPreviamente3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                138,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbAdoptadoPreviamente2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                138,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(80, 80, 80)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cbAdoptadoPreviamente5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                164,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbAdoptadoPreviamente4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                164,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbAdoptadoPreviamente1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                164,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(372, 372, 372))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(tfCorreo,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfCorreo1,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(tfNombre,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                446,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jComboBox2,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                105,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(34, 34, 34))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 177,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbAdoptadoPreviamente)
                                        .addComponent(cbAdoptadoPreviamente4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbAdoptadoPreviamente1)
                                        .addComponent(cbAdoptadoPreviamente3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbAdoptadoPreviamente2)
                                        .addComponent(cbAdoptadoPreviamente5))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 221, 25, 199);
        add(jPanel2, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Expediente Medico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 451, 0, 0);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private String panelAnterior = "CATALOGO";

    /**
     * Establece el nombre del panel anterior para poder regresar a él.
     * 
     * @param panel Nombre del panel anterior.
     */
    public void setPanelAnterior(String panel) {
        this.panelAnterior = panel;
    }

    /**
     * Configura los campos del formulario como de solo lectura.
     */
    public void configurarModoLectura() {
        // Deshabilitar campos
        tfNombre.setEditable(false); // Condición
        tfCorreo.setEditable(false); // Alergias
        tfCorreo1.setEditable(false); // Tratamientos previos

        // Deshabilitar checkboxes
        cbAdoptadoPreviamente.setEnabled(false);
        cbAdoptadoPreviamente1.setEnabled(false);
        cbAdoptadoPreviamente2.setEnabled(false);
        cbAdoptadoPreviamente3.setEnabled(false);
        cbAdoptadoPreviamente4.setEnabled(false);
        cbAdoptadoPreviamente5.setEnabled(false);

        // Ocultar botón de guardar/siguiente
        // btnSiguiente is not defined in this scope, assuming it might be added later
        // or is a typo.
        // For now, commenting it out to avoid compilation errors.
        // if (btnSiguiente != null) {
        // btnSiguiente.setVisible(false);
        // }
    }

    /**
     * Carga los datos médicos de la mascota en el formulario.
     * 
     * @param mascota DTO de la mascota con los datos a cargar.
     */
    public void cargarDatos(gestion.mascotasarchivadas.dtos.MascotaArchivoDTO mascota) {
        if (mascota == null) {
            System.out.println("DEBUG: ExpedienteMedico - Mascota es NULL");
            return;
        }

        System.out.println("DEBUG: ExpedienteMedico - Cargando datos. Alergias: " + mascota.getAlergias()
                + ", Vacunas: " + mascota.getExpedienteMedico());

        // Cargar datos básicos
        tfNombre.setText(mascota.getEstadoSalud()); // Condición general

        // Cargar datos del expediente si existen
        tfCorreo.setText(mascota.getAlergias() != null ? mascota.getAlergias() : ""); // Alergias
        tfCorreo1.setText(mascota.getCondicionesEspeciales() != null ? mascota.getCondicionesEspeciales() : ""); // Condiciones
                                                                                                                 // Especiales

        if (mascota.getNivelEnergia() != null) {
            jComboBox2.setSelectedItem(mascota.getNivelEnergia());
        }

        // Parsear expediente médico si existe (el string de vacunas construido en el
        // backend)
        String expediente = mascota.getExpedienteMedico();
        if (expediente != null) {
            // Marcar checkboxes si el texto contiene la palabra clave
            cbAdoptadoPreviamente.setSelected(expediente.contains("Rabia"));
            cbAdoptadoPreviamente1.setSelected(expediente.contains("Desparasitación Externa"));
            cbAdoptadoPreviamente2.setSelected(expediente.contains("Bordetella"));
            cbAdoptadoPreviamente3.setSelected(expediente.contains("Múltiple"));
            cbAdoptadoPreviamente4.setSelected(expediente.contains("Desparasitación Interna"));
            cbAdoptadoPreviamente5.setSelected(expediente.contains("Esterilizado"));
        }
    }

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_regresarActionPerformed
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.mostrarPanel(panelAnterior);
        }
    }// GEN-LAST:event_btn_regresarActionPerformed

    private void cbAdoptadoPreviamenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamenteActionPerformed

    private void cbAdoptadoPreviamente1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamente1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamente1ActionPerformed

    private void cbAdoptadoPreviamente2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamente2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamente2ActionPerformed

    private void cbAdoptadoPreviamente4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamente4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamente4ActionPerformed

    private void cbAdoptadoPreviamente3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamente3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamente3ActionPerformed

    private void cbAdoptadoPreviamente5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamente5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamente5ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnSiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JCheckBox cbAdoptadoPreviamente;
    private javax.swing.JCheckBox cbAdoptadoPreviamente1;
    private javax.swing.JCheckBox cbAdoptadoPreviamente2;
    private javax.swing.JCheckBox cbAdoptadoPreviamente3;
    private javax.swing.JCheckBox cbAdoptadoPreviamente4;
    private javax.swing.JCheckBox cbAdoptadoPreviamente5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfCorreo1;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
