/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

/**
 *
 * @author angel
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        configurarPaneles();
    }

    // Variables para los paneles
    private CatalogoMascotasArchivadas panelCatalogo;
    private DetallesMascota panelDetalles;
    private EliminarMascota panelEliminar;
    private ReactivarMascota panelReactivar;
    private ExpedienteMedico panelExpediente;

    // Método para configurar CardLayout
    private void configurarPaneles() {
        // Configurar CardLayout
        panelContenidoDinamico.setLayout(new java.awt.CardLayout());

        // Crear paneles
        panelCatalogo = new CatalogoMascotasArchivadas();
        panelDetalles = new DetallesMascota();
        panelEliminar = new EliminarMascota();
        panelReactivar = new ReactivarMascota();
        panelExpediente = new ExpedienteMedico();

        // Agregar al CardLayout
        panelContenidoDinamico.add(panelCatalogo, "CATALOGO");
        panelContenidoDinamico.add(panelDetalles, "DETALLES");
        panelContenidoDinamico.add(panelEliminar, "ELIMINAR");
        panelContenidoDinamico.add(panelReactivar, "REACTIVAR");
        panelContenidoDinamico.add(panelExpediente, "EXPEDIENTE");

        // Mostrar catálogo por defecto
        mostrarPanel("CATALOGO");
    }

    // Método para cambiar de panel
    public void mostrarPanel(String nombrePanel) {
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenidoDinamico.getLayout();
        cl.show(panelContenidoDinamico, nombrePanel);
    }

    public DetallesMascota obtenerPanelDetalles() {
        return panelDetalles;
    }

    public EliminarMascota obtenerPanelEliminar() {
        return panelEliminar;
    }

    public ReactivarMascota obtenerPanelReactivar() {
        return panelReactivar;
    }

    public ExpedienteMedico obtenerPanelExpediente() {
        return panelExpediente;
    }

    // Método para recargar el catálogo después de eliminar/reactivar
    public void recargarCatalogo() {
        if (panelCatalogo != null) {
            panelCatalogo.cargarCatalogo();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoDinamico = new javax.swing.JPanel();
        panelCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        lblUserImage = new javax.swing.JLabel();
        lblUserImage1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_InicioAdmin = new javax.swing.JButton();
        btn_cerrarSesion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenidoDinamico.setBackground(new java.awt.Color(219, 213, 195));

        javax.swing.GroupLayout panelContenidoDinamicoLayout = new javax.swing.GroupLayout(panelContenidoDinamico);
        panelContenidoDinamico.setLayout(panelContenidoDinamicoLayout);
        panelContenidoDinamicoLayout.setHorizontalGroup(
                panelContenidoDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        panelContenidoDinamicoLayout.setVerticalGroup(
                panelContenidoDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 685, Short.MAX_VALUE));

        panelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        panelCabecera.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 110, 33));
        jLabel1.setText("LA VIDA ES BELLA");

        btn_inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_inicio.setForeground(new java.awt.Color(0, 0, 0));
        btn_inicio.setText("INICIO");
        btn_inicio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_inicio.setBorderPainted(false);
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        lblUserImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserImageMouseClicked(evt);
            }
        });

        lblUserImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserImage1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mascotas Archivadas");

        btn_InicioAdmin.setBackground(new java.awt.Color(153, 0, 0));
        btn_InicioAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_InicioAdmin.setText("Inicio Admin");
        btn_InicioAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_InicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InicioAdminActionPerformed(evt);
            }
        });

        btn_cerrarSesion1.setBackground(new java.awt.Color(153, 0, 0));
        btn_cerrarSesion1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cerrarSesion1.setText("Cerrar Sesion");
        btn_cerrarSesion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
                panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCabeceraLayout.createSequentialGroup()
                                .addGroup(panelCabeceraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelCabeceraLayout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(jLabel1)
                                                .addGap(251, 251, 251)
                                                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 182,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(197, 197, 197)
                                                .addComponent(btn_InicioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblUserImage)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_cerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelCabeceraLayout.createSequentialGroup()
                                                .addGap(506, 506, 506)
                                                .addComponent(jLabel2)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCabeceraLayout.createSequentialGroup()
                                        .addGap(597, 597, 597)
                                        .addComponent(lblUserImage1)
                                        .addContainerGap(598, Short.MAX_VALUE))));
        panelCabeceraLayout.setVerticalGroup(
                panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout
                                .createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addGroup(panelCabeceraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelCabeceraLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btn_InicioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelCabeceraLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1))
                                        .addComponent(btn_cerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCabeceraLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lblUserImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(33, Short.MAX_VALUE))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelContenidoDinamico, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelContenidoDinamico, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_inicioActionPerformed
        // Volver al catálogo de mascotas archivadas
        mostrarPanel("CATALOGO");
    }// GEN-LAST:event_btn_inicioActionPerformed

    private void lblUserImageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblUserImageMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_lblUserImageMouseClicked

    private void lblUserImage1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblUserImage1MouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_lblUserImage1MouseClicked

    private void btn_InicioAdminActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_InicioAdminActionPerformed
        try {
            // Usamos Reflection para cargar JPAdmin dinámicamente
            Class<?> jpAdminClass = Class.forName("gui.JPAdmin");
            javax.swing.JPanel jpAdmin = (javax.swing.JPanel) jpAdminClass.getDeclaredConstructor().newInstance();

            // Obtener el Frame actual
            javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities
                    .getWindowAncestor(btn_InicioAdmin);
            if (frame != null) {
                frame.setContentPane(jpAdmin);
                frame.revalidate();
                frame.repaint();
                frame.setTitle("Panel de Administración");
                frame.pack();
                frame.setLocationRelativeTo(null);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al volver al menú: " + ex.getMessage());
        }
    }// GEN-LAST:event_btn_InicioAdminActionPerformed

    private void btn_cerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_cerrarSesion1ActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Seguro que desea cerrar sesión?",
                "Cerrar Sesión",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Usamos Reflection para crear nuevo FrmInicioSesion
                Class<?> loginClass = Class.forName("gui.FrmInicioSesion");
                javax.swing.JFrame loginFrame = (javax.swing.JFrame) loginClass.getDeclaredConstructor().newInstance();
                loginFrame.setVisible(true);

                // Cerrar ventana actual
                javax.swing.JFrame currentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities
                        .getWindowAncestor(btn_cerrarSesion1);
                if (currentFrame != null)
                    currentFrame.dispose();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }// GEN-LAST:event_btn_cerrarSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_InicioAdmin;
    private javax.swing.JButton btn_cerrarSesion1;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JLabel lblUserImage1;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelContenidoDinamico;
    // End of variables declaration//GEN-END:variables
}
