/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

/**
 *
 * @author angel
 */
public class ReactivarMascota extends javax.swing.JPanel {

    private String mascotaId;
    private gestion.mascotasarchivadas.control.ControlPresentacion controlPresentacion;

    /**
     * Creates new form ReactivarMascota
     */
    public ReactivarMascota() {
        initComponents();
        this.controlPresentacion = new gestion.mascotasarchivadas.control.ControlPresentacion();
        configurarCamposNoEditables();
    }

    public void setMascotaId(String id) {
        this.mascotaId = id;
        cargarDatosMascota();
    }

    private void configurarCamposNoEditables() {
        tfNombre.setEditable(false);
        tfEspecie.setEnabled(false);
        tfRaza.setEditable(false);
        tfColor.setEditable(false);
        tfEdad.setEditable(false);
        tfPeso.setEditable(false);
        tfDescripcion.setEditable(false);
    }

    private void cargarDatosMascota() {
        if (mascotaId == null || mascotaId.isEmpty()) {
            return;
        }

        try {
            gestion.mascotasarchivadas.dtos.MascotaArchivoDTO mascota = controlPresentacion.obtenerDetalles(mascotaId);

            if (mascota != null) {
                tfNombre.setText(mascota.getNombre());
                tfRaza.setText(mascota.getRaza());
                tfColor.setText(mascota.getColor());
                tfEdad.setText(String.valueOf(mascota.getEdad()));
                tfPeso.setText(String.valueOf(mascota.getPeso()));
                tfDescripcion.setText(mascota.getEstadoSalud());
                tfEspecie.setText(mascota.getEspecie());
                tfPersonalidad.setText(mascota.getPersonalidad());

                if (mascota.getUrlImagen() != null && !mascota.getUrlImagen().isEmpty()) {
                    try {
                        java.io.File imageFile = new java.io.File(mascota.getUrlImagen());
                        if (imageFile.exists()) {
                            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imageFile.getAbsolutePath());
                            java.awt.Image img = icon.getImage().getScaledInstance(200, 200,
                                    java.awt.Image.SCALE_SMOOTH);
                            lbl_Img.setIcon(new javax.swing.ImageIcon(img));
                            lbl_Img.setText("");
                        }
                    } catch (Exception e) {
                        System.err.println("Error al cargar imagen: " + e.getMessage());
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        tfDescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfEdad = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        tfRaza = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfColor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lbl_Img = new javax.swing.JLabel();
        btnAgregarExp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfPersonalidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEspecie = new javax.swing.JTextField();

        setBackground(new java.awt.Color(219, 213, 195));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        btnCancelar.setText("Regresar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfDescripcion.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estado salud");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Edad");

        tfEdad.setBackground(new java.awt.Color(204, 204, 204));

        tfNombre.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Especie");

        btnSiguiente.setBackground(new java.awt.Color(0, 153, 51));
        btnSiguiente.setText("REACTIVAR");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        tfRaza.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Raza");

        tfColor.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Color");

        tfPeso.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Peso");

        lbl_Img.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAgregarExp.setText("Ver Expediente Medico");
        btnAgregarExp.setActionCommand("EditarExpedienteMedico");
        btnAgregarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExpActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Personalidad");

        tfPersonalidad.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Seguro que desea REACTIVAR a esta mascota?");

        tfEspecie.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))
                                                .addContainerGap(740, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(btnCancelar,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnSiguiente,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 201,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(131, 131, 131)
                                                                .addComponent(btnAgregarExp))
                                                        .addComponent(tfDescripcion,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(tfEdad,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                139,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(25, 25, 25)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(tfColor,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        211,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(tfPeso,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        158,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel14))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(jLabel9)
                                                                                        .addGap(0, 136,
                                                                                                Short.MAX_VALUE))
                                                                                .addComponent(tfPersonalidad))))
                                                .addGap(34, 34, 34))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(113, 113, 113))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(tfEspecie,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                139,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)))
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(tfRaza)
                                                                .addGap(34, 34, 34))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(lbl_Img, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(294, 294, 294))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tfRaza, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfEspecie, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfEdad,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel14)
                                                                        .addComponent(jLabel9)))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfPersonalidad,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(46, Short.MAX_VALUE)));

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        // Regresar a Detalles
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.mostrarPanel("DETALLES");
        }
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
        // Confirma si realmente desea reactivar
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea REACTIVAR a esta mascota?\n\n" +
                        "La mascota volverá a estar DISPONIBLE en el catálogo principal.\n" +
                        "Se eliminará de la lista de mascotas archivadas.",
                "Confirmar Reactivación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Reactivar mascota (volver a disponible=true)
                gestion.mascotasarchivadas.dtos.ResultadoOperacion resultado = controlPresentacion
                        .reactivarMascota(this.mascotaId);

                if (resultado.isExitoso()) {
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            resultado.getMensaje(),
                            "Reactivación Exitosa",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Recargar catálogo y regresar
                    FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (frame != null) {
                        frame.recargarCatalogo();
                        frame.mostrarPanel("CATALOGO");
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            resultado.getMensaje(),
                            "Error al Reactivar",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error inesperado al reactivar la mascota: " + e.getMessage(),
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_btnSiguienteActionPerformed


    private void btnAgregarExpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarExpActionPerformed
        try {
            if (mascotaId == null || mascotaId.isEmpty()) {
                return;
            }

            FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (frame != null) {
                ExpedienteMedico expedientePanel = frame.obtenerPanelExpediente();
                if (expedientePanel != null) {
                    // Obtener mascota completa con datos medicos
                    gestion.mascotasarchivadas.dtos.MascotaArchivoDTO mascota = controlPresentacion
                            .obtenerDetalles(mascotaId);

                    System.out.println("DEBUG: ReactivarMascota - Mascota recuperada: "
                            + (mascota != null ? mascota.getNombre() : "null"));
                    if (mascota != null) {
                        System.out.println("DEBUG: ReactivarMascota - Alergias: " + mascota.getAlergias());
                        System.out.println("DEBUG: ReactivarMascota - Expediente: " + mascota.getExpedienteMedico());
                    }

                    // Configurar panel
                    expedientePanel.cargarDatos(mascota);
                    expedientePanel.configurarModoLectura();
                    expedientePanel.setPanelAnterior("REACTIVAR");

                    // Mostrar panel
                    frame.mostrarPanel("EXPEDIENTE");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir expediente: " + e.getMessage());
        }
    }// GEN-LAST:event_btnAgregarExpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarExp;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Img;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfEspecie;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPersonalidad;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfRaza;
    // End of variables declaration//GEN-END:variables
}
