/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.flujoAdoptar;

/**
 *
 * @author Erick
 */
public class FrmInfoVivienda extends javax.swing.JPanel {
    private control.ControlPresentacion controlPresentacion;

    /**
     * Creates new form JPInfoVivienda
     */
    public FrmInfoVivienda() {
        initComponents();
        configurarCheckboxes();
    }

    private void configurarCheckboxes() {
        // Hacer que los checkboxes de mascotas sean mutuamente excluyentes
        CbSiTieneMasmascotas.addActionListener(e -> {
            if (CbSiTieneMasmascotas.isSelected()) {
                CbNoTieneMasmascotas.setSelected(false);
            }
        });

        CbNoTieneMasmascotas.addActionListener(e -> {
            if (CbNoTieneMasmascotas.isSelected()) {
                CbSiTieneMasmascotas.setSelected(false);
            }
        });

        // Hacer que los checkboxes de niños sean mutuamente excluyentes
        CbSiTieneNinos.addActionListener(e -> {
            if (CbSiTieneNinos.isSelected()) {
                CbNoTieneninos.setSelected(false);
            }
        });

        CbNoTieneninos.addActionListener(e -> {
            if (CbNoTieneninos.isSelected()) {
                CbSiTieneNinos.setSelected(false);
            }
        });
    }

    public void setControlPresentacion(control.ControlPresentacion controlPresentacion) {
        this.controlPresentacion = controlPresentacion;
    }

    private String rutaImagenSeleccionada; // Almacena la ruta de la imagen seleccionada

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        tfCondicionesHogar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnSeleccionarReferencia = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CbSiTieneMasmascotas = new javax.swing.JCheckBox();
        CbNoTieneMasmascotas = new javax.swing.JCheckBox();
        CbSiTieneNinos = new javax.swing.JCheckBox();
        CbNoTieneninos = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(219, 213, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Solicitud de Adopciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Paso 2: Información de la Vivienda");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de Vivienda");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setText("Propia");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2.setText("Rentada");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Condiciones del Hogar");

        tfCondicionesHogar.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("¿Hay otros animales o niños en casa?");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Disponibilidad de Tiempo(Horas en que la mascota estará sola)");

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 - 2 Horas", "2 - 4 Horas", "4 - 6 Horas", "6 - 8 Horas", "8+ horas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Adjuntar Evidencia (Opcional)");

        btnSeleccionarReferencia.setBackground(new java.awt.Color(204, 204, 204));
        btnSeleccionarReferencia.setText("Click para subir foto del area donde vivirá la máscota");
        btnSeleccionarReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarReferenciaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(0, 102, 51));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tienes más mascotas");

        CbSiTieneMasmascotas.setText("Si");

        CbNoTieneMasmascotas.setText("No");

        CbSiTieneNinos.setText("Si");

        CbNoTieneninos.setText("No");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tienes niños");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(tfCondicionesHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSeleccionarReferencia)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                                        .addComponent(btnSiguiente))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox2))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CbSiTieneNinos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CbNoTieneninos))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CbSiTieneMasmascotas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CbNoTieneMasmascotas))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCondicionesHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CbSiTieneMasmascotas)
                    .addComponent(CbNoTieneMasmascotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CbSiTieneNinos)
                    .addComponent(CbNoTieneninos))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionarReferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnCancelar))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (controlPresentacion != null) {
            controlPresentacion.regresarDesdeFrmInfoVivienda();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed


    private void btnSeleccionarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {
        // Crear selector de archivos
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar imagen de la vivienda");

        // Filtro para imágenes
        javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (*.jpg, *.png, *.jpeg)", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);

        // Mostrar diálogo
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            // Obtener archivo seleccionado
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();
            rutaImagenSeleccionada = archivoSeleccionado.getAbsolutePath();

            // Mostrar confirmación
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Imagen seleccionada: " + archivoSeleccionado.getName(),
                    "Imagen añadida",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
        if (controlPresentacion != null) {
            // Obtener datos del formulario
            String condicionesHogar = tfCondicionesHogar.getText().trim();
            String tiempoDisponibilidad = (String) jComboBox1.getSelectedItem();

            // Determinar tipo de vivienda
            String tipoVivienda = "";
            if (jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Por favor seleccione solo una opción: Propia o Rentada",
                        "Error de selección",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            } else if (jCheckBox1.isSelected()) {
                tipoVivienda = "Propia";
            } else if (jCheckBox2.isSelected()) {
                tipoVivienda = "Rentada";
            }

            // VALIDACIONES

            // 1. Validar tipo de vivienda
            if (tipoVivienda.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Por favor seleccione el tipo de vivienda (Propia o Rentada)",
                        "Campo requerido",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Validar condiciones del hogar
            if (condicionesHogar.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Por favor describa las condiciones de su hogar",
                        "Campo requerido",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                tfCondicionesHogar.requestFocus();
                return;
            }

            // 3. Validar selección de mascotas
            if (!CbSiTieneMasmascotas.isSelected() && !CbNoTieneMasmascotas.isSelected()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Por favor indique si tiene otras mascotas",
                        "Campo requerido",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 4. Validar selección de niños
            if (!CbSiTieneNinos.isSelected() && !CbNoTieneninos.isSelected()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Por favor indique si tiene niños en casa",
                        "Campo requerido",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Crear el DTO con los datos validados
            DTOS.InfoViviendaDTO info = new DTOS.InfoViviendaDTO();
            info.setTipoVivienda(tipoVivienda);
            info.setCondicionesHogar(condicionesHogar);
            info.setTiempoDisponibilidad(tiempoDisponibilidad);
            info.setUrlImagenVivienda(rutaImagenSeleccionada);

            // Obtener valores de los checkboxes
            info.setTieneOtrasMascotas(CbSiTieneMasmascotas.isSelected());
            info.setTieneNinos(CbSiTieneNinos.isSelected());

            // Guardar la información de vivienda
            controlPresentacion.guardarInfoVivienda(info);
        } else {
            System.err.println("Error: No hay referencia al ControlPresentacion");
        }
    }// GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CbNoTieneMasmascotas;
    private javax.swing.JCheckBox CbNoTieneninos;
    private javax.swing.JCheckBox CbSiTieneMasmascotas;
    private javax.swing.JCheckBox CbSiTieneNinos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionarReferencia;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCondicionesHogar;
    // End of variables declaration//GEN-END:variables
}
