/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.flujoAdoptar;

import gui.JPContacto;
import gui.JPSolicitudes;

/**
 *
 * @author angel
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;
    private MenuMostrarEspecies menuMostrarEspecies;
    private FrmInfoPersonal frmInfoPersonal;
    private FrmInfoVivienda frmInfoVivienda;
    private FrmRazonesAntecedentes frmRazonesAntecedentes;
    private JPInfoResumen frmInfoResumen;
    private FrmPerfil frmPerfil;

    private JPSolicitudes jpSolicitudes;
    private gui.FrmCorreoConfirmacion frmCorreoConfirmacion;

    private control.ControlPresentacion controlPresentacion;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        initCardLayout();
    }

    private void initCardLayout() {
        cardLayout = new java.awt.CardLayout();
        panelContenidoDinamico.setLayout(cardLayout);

        // Instanciar paneles
        menuMostrarEspecies = new MenuMostrarEspecies();
        frmInfoPersonal = new FrmInfoPersonal();
        frmInfoVivienda = new FrmInfoVivienda();
        frmRazonesAntecedentes = new FrmRazonesAntecedentes();
        frmInfoResumen = new JPInfoResumen();
        jpSolicitudes = new JPSolicitudes();
        frmPerfil = new FrmPerfil();
        frmCorreoConfirmacion = new gui.FrmCorreoConfirmacion();

        // Agregar al CardLayout con identificadores clave
        panelContenidoDinamico.add(menuMostrarEspecies, "inicio");
        panelContenidoDinamico.add(jpSolicitudes, "solicitudes");
        panelContenidoDinamico.add(new JPContacto(), "contacto");
        panelContenidoDinamico.add(frmInfoPersonal, "infoPersonal"); // Agregar al layout
        panelContenidoDinamico.add(frmInfoVivienda, "infoVivienda");
        panelContenidoDinamico.add(frmRazonesAntecedentes, "razonesAntecedentes");
        panelContenidoDinamico.add(frmInfoResumen, "infoResumen");
        panelContenidoDinamico.add(frmPerfil, "perfil");
        panelContenidoDinamico.add(frmCorreoConfirmacion, "confirmacion");

        cardLayout.show(panelContenidoDinamico, "inicio");
    }

    public void setControl(control.ControlPresentacion control) {
        this.controlPresentacion = control; // Guardar referencia

        if (menuMostrarEspecies != null) {
            menuMostrarEspecies.setControlPresentacion(control);
        }
        if (frmInfoPersonal != null) {
            frmInfoPersonal.setControlPresentacion(control);
        }
        if (frmInfoVivienda != null) {
            frmInfoVivienda.setControlPresentacion(control);
        }
        if (frmRazonesAntecedentes != null) {
            frmRazonesAntecedentes.setControlPresentacion(control);
        }
        if (frmInfoResumen != null) {
            frmInfoResumen.setControlPresentacion(control);
        }
        if (jpSolicitudes != null) {
            jpSolicitudes.setControlPresentacion(control);
        }
        if (frmPerfil != null) {
            frmPerfil.setControlPresentacion(control);
        }
    }

    public MenuMostrarEspecies getMenuMostrarEspecies() {
        return menuMostrarEspecies;
    }

    public void mostrarInicio() {
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "inicio");
        }
    }

    public void mostrarInfoPersonal() {
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "infoPersonal");
        }
    }

    public void mostrarInfoVivienda() {
        if (cardLayout != null)
            cardLayout.show(panelContenidoDinamico, "infoVivienda");
    }

    public void mostrarRazonesAntecedentes() {
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "razonesAntecedentes");
        }
    }

    public void mostrarInfoResumen() {
        if (cardLayout != null) {
            if (frmInfoResumen != null) {
                frmInfoResumen.cargarDatos();
            }
            cardLayout.show(panelContenidoDinamico, "infoResumen");
        }
    }

    public void mostrarConfirmacion() {
        if (cardLayout != null) {
            if (frmCorreoConfirmacion != null) {
                frmCorreoConfirmacion.setControlPresentacion(controlPresentacion);
                frmCorreoConfirmacion.cargarDatos();
            }
            cardLayout.show(panelContenidoDinamico, "confirmacion");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        btn_solicitudes = new javax.swing.JButton();
        btn_contacto = new javax.swing.JButton();
        lblUserImage = new javax.swing.JLabel();
        panelContenidoDinamico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        panelCabecera.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 110, 33));
        jLabel1.setText("LA VIDA ES BELLA");

        btn_inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_inicio.setText("Inicio");
        btn_inicio.setBorder(null);
        btn_inicio.setBorderPainted(false);
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_solicitudes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_solicitudes.setText("Mis Solicitudes");
        btn_solicitudes.setBorder(null);
        btn_solicitudes.setBorderPainted(false);
        btn_solicitudes.setContentAreaFilled(false);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_contacto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_contacto.setText("Contacto");
        btn_contacto.setBorder(null);
        btn_contacto.setBorderPainted(false);
        btn_contacto.setContentAreaFilled(false);
        btn_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contactoActionPerformed(evt);
            }
        });

        lblUserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sources/icon-7797704_1280.png"))); // NOI18N
        lblUserImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(122, 122, 122)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblUserImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        panelContenidoDinamico.setBackground(new java.awt.Color(235, 229, 220));
        panelContenidoDinamico.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenidoDinamicoLayout = new javax.swing.GroupLayout(panelContenidoDinamico);
        panelContenidoDinamico.setLayout(panelContenidoDinamicoLayout);
        panelContenidoDinamicoLayout.setHorizontalGroup(
            panelContenidoDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        panelContenidoDinamicoLayout.setVerticalGroup(
            panelContenidoDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenidoDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelContenidoDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserImageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblUserImageMouseClicked
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "perfil");
        }
    }// GEN-LAST:event_lblUserImageMouseClicked

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_inicioActionPerformed
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "inicio");
        }
    }// GEN-LAST:event_btn_inicioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_solicitudesActionPerformed
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "solicitudes");
        }
    }// GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_contactoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_contactoActionPerformed
        if (cardLayout != null) {
            cardLayout.show(panelContenidoDinamico, "contacto");
        }
    }// GEN-LAST:event_btn_contactoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_contacto;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_solicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelContenidoDinamico;
    // End of variables declaration//GEN-END:variables
}
