/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.flujoAdoptar;

/**
 * Panel para capturar las razones de adopción y los antecedentes con mascotas
 * del solicitante.
 * También requiere que el usuario acepte las condiciones de seguimiento.
 * 
 * @author angel
 */
public class FrmRazonesAntecedentes extends javax.swing.JPanel {

        /** Controlador de presentación para la gestión de la lógica. */
        private control.ControlPresentacion controlPresentacion;

        /**
         * Crea una nueva instancia del panel FrmRazonesAntecedentes.
         * Inicializa los componentes gráficos.
         */
        public FrmRazonesAntecedentes() {
                initComponents();
        }

        /**
         * Establece el controlador de presentación.
         * 
         * @param controlPresentacion El controlador a asociar con este panel.
         */
        public void setControlPresentacion(control.ControlPresentacion controlPresentacion) {
                this.controlPresentacion = controlPresentacion;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                tfMotivo = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                tfAntecedentes = new javax.swing.JTextField();
                cbAceptarCondiciones = new javax.swing.JCheckBox();
                btnCancelar = new javax.swing.JButton();
                btnSiguiente = new javax.swing.JButton();

                jPanel1.setBackground(new java.awt.Color(219, 213, 195));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                jLabel2.setText("Solicitud de Adopciones");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel3.setText("Paso 3: Experiencias y Antecedentes");

                tfMotivo.setBackground(new java.awt.Color(204, 204, 204));

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setText("Motivo de adopción");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setText("Antecedentes de Mascotas");

                tfAntecedentes.setBackground(new java.awt.Color(204, 204, 204));

                cbAceptarCondiciones.setText("Acepto las condiciones de seguimiento post-adopción del refugio");
                cbAceptarCondiciones.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbAceptarCondicionesActionPerformed(evt);
                        }
                });

                btnCancelar.setText("Cancelar");
                btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarActionPerformed(evt);
                        }
                });

                btnSiguiente.setBackground(new java.awt.Color(0, 102, 0));
                btnSiguiente.setText("Siguiente");
                btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSiguienteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(32, 32, 32)
                                                                                                .addComponent(jLabel3))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(47, 47, 47)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(jLabel5)
                                                                                                                                .addComponent(jLabel4)
                                                                                                                                .addComponent(cbAceptarCondiciones)
                                                                                                                                .addComponent(tfMotivo)
                                                                                                                                .addComponent(tfAntecedentes,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                401,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(btnCancelar)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                572,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(btnSiguiente)))))
                                                                .addGap(48, 48, 48)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfMotivo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                80,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(tfAntecedentes,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                111, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cbAceptarCondiciones)
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnCancelar)
                                                                                .addComponent(btnSiguiente))
                                                                .addGap(28, 28, 28)));

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 830, 450));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                1300,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                720,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Maneja el evento del checkbox de aceptar condiciones (sin implementación
         * actual).
         * 
         * @param evt El evento de acción.
         */
        private void cbAceptarCondicionesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAceptarCondicionesActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_cbAceptarCondicionesActionPerformed

        /**
         * Maneja el evento de cancelar el proceso.
         * Regresa a la pantalla anterior.
         * 
         * @param evt El evento de acción.
         */
        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
                if (controlPresentacion != null) {
                        controlPresentacion.regresarDesdeFrmRazonesAntecedentes();
                }
        }// GEN-LAST:event_btnCancelarActionPerformed

        /**
         * Valida los datos ingresados y guarda las razones y antecedentes.
         * Verifica que se hayan llenado los campos y aceptado las condiciones.
         * 
         * @param evt El evento de acción.
         */
        private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
                if (controlPresentacion != null) {
                        // Obtener datos del formulario
                        String motivoAdopcion = tfMotivo.getText().trim();
                        String antecedentesMascotas = tfAntecedentes.getText().trim();
                        boolean aceptaSeguimiento = cbAceptarCondiciones.isSelected();

                        // VALIDACIONES

                        // 1. Validar motivo de adopción
                        if (motivoAdopcion.isEmpty()) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Por favor indique el motivo de adopción",
                                                "Campo requerido",
                                                javax.swing.JOptionPane.WARNING_MESSAGE);
                                tfMotivo.requestFocus();
                                return;
                        }

                        // 2. Validar antecedentes de mascotas
                        if (antecedentesMascotas.isEmpty()) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Por favor describa sus antecedentes con mascotas",
                                                "Campo requerido",
                                                javax.swing.JOptionPane.WARNING_MESSAGE);
                                tfAntecedentes.requestFocus();
                                return;
                        }

                        // 3. Validar que acepte las condiciones
                        if (!aceptaSeguimiento) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Debe aceptar las condiciones de seguimiento post-adopción para continuar",
                                                "Condiciones requeridas",
                                                javax.swing.JOptionPane.WARNING_MESSAGE);
                                return;
                        }

                        // Crear el DTO con los datos validados
                        DTOS.RazonesAntecedentesDTO razones = new DTOS.RazonesAntecedentesDTO();
                        razones.setMotivoAdopcion(motivoAdopcion);
                        razones.setAntecedentesMascotas(antecedentesMascotas);
                        razones.setAceptaSeguimiento(aceptaSeguimiento);

                        // Guardar las razones y antecedentes
                        controlPresentacion.guardarRazonesAntecedentes(razones);
                } else {
                        System.err.println("Error: No hay referencia al ControlPresentacion");
                }
        }// GEN-LAST:event_btnSiguienteActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        /** Botón para cancelar y regresar */
        private javax.swing.JButton btnCancelar;
        /** Botón para continuar al siguiente paso */
        private javax.swing.JButton btnSiguiente;
        /** Checkbox para aceptar condiciones de seguimiento */
        private javax.swing.JCheckBox cbAceptarCondiciones;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        /** Campo de texto para antecedentes con mascotas */
        private javax.swing.JTextField tfAntecedentes;
        /** Campo de texto para motivo de adopción */
        private javax.swing.JTextField tfMotivo;
        // End of variables declaration//GEN-END:variables
}
