/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.flujoAdoptar;

import DTOS.CitaDisponibleDTO;
import control.ControlPresentacion;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
/**
 * Diálogo modal para seleccionar una cita disponible de una lista.
 * 
 * @author angel
 */
public class FrmSeleccionarCita extends javax.swing.JDialog {

    private ControlPresentacion control;
    private CitaDisponibleDTO citaSeleccionada;
    private DefaultTableModel modeloTabla;

    /**
     * Crea un nuevo formulario FrmSeleccionarCita.
     * 
     * @param parent  Frame padre.
     * @param modal   Si es modal o no.
     * @param control Controlador de presentación.
     */
    public FrmSeleccionarCita(java.awt.Frame parent, boolean modal, ControlPresentacion control) {
        super(parent, modal);
        this.control = control;
        initComponents();
        inicializarTabla();
        cargarCitasDisponibles();
        this.setLocationRelativeTo(parent);
    }

    /**
     * Inicializa el modelo de la tabla de citas.
     */
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTabla.addColumn("ID"); // Oculto
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Hora");

        tblCitas.setModel(modeloTabla);

        // Ocultar columna ID
        tblCitas.getColumnModel().getColumn(0).setMinWidth(0);
        tblCitas.getColumnModel().getColumn(0).setMaxWidth(0);
        tblCitas.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * Carga las citas disponibles desde el controlador.
     */
    private void cargarCitasDisponibles() {
        if (control == null)
            return;

        List<CitaDisponibleDTO> citas = control.obtenerCitasDisponibles();
        modeloTabla.setRowCount(0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (CitaDisponibleDTO cita : citas) {
            modeloTabla.addRow(new Object[] {
                    cita, // Guardamos el objeto completo en la columna oculta
                    sdf.format(cita.getFecha()),
                    cita.getHora()
            });
        }
    }

    /**
     * Obtiene la cita seleccionada.
     * 
     * @return DTO de la cita seleccionada.
     */
    public CitaDisponibleDTO getCitaSeleccionada() {
        return citaSeleccionada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar Cita Disponible");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Fechas Disponibles para Cita");

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        tblCitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblCitas);

        btnSeleccionar.setBackground(new java.awt.Color(0, 102, 51));
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione una fecha y hora de la lista:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnCancelar)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnSeleccionar))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 375,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addContainerGap(28, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSeleccionar)
                                        .addComponent(btnCancelar))
                                .addContainerGap(21, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {
        int fila = tblCitas.getSelectedRow();
        if (fila >= 0) {
            citaSeleccionada = (CitaDisponibleDTO) modeloTabla.getValueAt(fila, 0);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor seleccione una cita de la lista",
                    "Selección requerida",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            // Recargar citas cada vez que se abre el diálogo
            cargarCitasDisponibles();
        }
        super.setVisible(visible);
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        citaSeleccionada = null;
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCitas;
    // End of variables declaration
}
