/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.flujoAdoptar.*;

/**
 * Panel de confirmación que notifica al usuario que su solicitud ha sido
 * enviada.
 * Muestra el correo electrónico al cual se envió la confirmación.
 * 
 * @author angel
 */
public class FrmCorreoConfirmacion extends javax.swing.JPanel {

    /** Controlador de presentación. */
    private control.ControlPresentacion controlPresentacion;

    /**
     * Crea una nueva instancia del panel de confirmación.
     * Inicializa los componentes visuales.
     */
    public FrmCorreoConfirmacion() {
        initComponents();
    }

    /**
     * Establece el controlador de presentación.
     * 
     * @param controlPresentacion El controlador a asociar.
     */
    public void setControlPresentacion(control.ControlPresentacion controlPresentacion) {
        this.controlPresentacion = controlPresentacion;
    }

    /**
     * Carga los datos confirma la visualización del correo del usuario.
     * Obtiene el correo del usuario actual desde el controlador y lo muestra.
     */
    public void cargarDatos() {
        if (controlPresentacion != null) {
            DTOS.UsuarioDTO usuario = controlPresentacion.getUsuarioActual();
            if (usuario != null && usuario.getInfoPersonal() != null) {
                String correo = usuario.getInfoPersonal().getCorreo();
                if (correo != null && !correo.isEmpty()) {
                    lblCorreo1.setText(correo);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        imgExito = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(219, 213, 195));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SOLICITUD ENVIADA EXITOSAMENTE!");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 830, 80));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("Hemos enviado la información al siguiente correo");
        jPanel3.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 840, -1));

        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo1.setText("correo");
        jPanel3.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 450, -1));

        imgExito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sources/listo.png"))); // NOI18N
        jPanel3.add(imgExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 280, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void cbAdoptadoPreviamenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgExito;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCorreo;
    /** Etiqueta que muestra el correo electrónico del usuario */
    private javax.swing.JLabel lblCorreo1;
    // End of variables declaration//GEN-END:variables
}
