/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.flujoAdoptar.*;

/**
 * Panel para mostrar mensajes de error al usuario de manera amigable.
 * Permite visualizar el detalle del error ocurrido.
 * 
 * @author angel
 */
public class FrmError extends javax.swing.JPanel {

    /** Controlador de presentación. */
    private control.ControlPresentacion controlPresentacion;

    /**
     * Crea una nueva instancia del panel de error.
     * Inicializa los componentes gráficos.
     */
    public FrmError() {
        initComponents();
    }

    /**
     * Establece el controlador de presentación.
     * 
     * @param controlPresentacion El controlador de presentación.
     */
    public void setControlPresentacion(control.ControlPresentacion controlPresentacion) {
        this.controlPresentacion = controlPresentacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(219, 213, 195));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblError.setForeground(new java.awt.Color(0, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("OCURRIÓ UN ERROR");
        jPanel3.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 830, 80));

        lblDetalle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDetalle.setForeground(new java.awt.Color(0, 0, 0));
        lblDetalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDetalle.setText("Error:");
        jPanel3.add(lblDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 450, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sources/error.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 280, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 532,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Establece el mensaje de error a mostrar en el panel.
     * 
     * @param mensaje El mensaje de error detallado.
     */
    public void setMensajeError(String mensaje) {
        if (lblDetalle != null) {
            lblDetalle.setText(mensaje);
        }
    }

    private void cbAdoptadoPreviamenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAdoptadoPreviamenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbAdoptadoPreviamenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    /** Etiqueta para mostrar el detalle del error */
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblError;
    // End of variables declaration//GEN-END:variables
}
