/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author angel
 */
import control.ControlPresentacion;

public class FrmInicioSesion extends javax.swing.JFrame {

        private ControlPresentacion controlPresentacion;

        /**
         * Creates new form FrmInicioSesion
         */
        public FrmInicioSesion() {
                initComponents();
                this.controlPresentacion = new ControlPresentacion();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jSeparator2 = new javax.swing.JSeparator();
                PfContra = new javax.swing.JPasswordField();
                PanelRegistro = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                btnRegistro = new javax.swing.JButton();
                PanelHead = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                btnIniciarS = new javax.swing.JButton();
                lblCorreo = new javax.swing.JLabel();
                TfCorreo = new javax.swing.JTextField();
                jSeparator1 = new javax.swing.JSeparator();
                limpiarCorreo = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jLabel2.setText("Contraseña");

                jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

                PfContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                PfContra.setBorder(null);
                PfContra.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PfContraActionPerformed(evt);
                        }
                });

                PanelRegistro.setBackground(new java.awt.Color(0, 153, 0));

                jLabel3.setBackground(new java.awt.Color(255, 255, 255));
                jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("¿No tienes cuenta?");

                jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Registrate");

                btnRegistro.setBackground(new java.awt.Color(153, 255, 153));
                btnRegistro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
                btnRegistro.setText("¡AQUI!");
                btnRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                btnRegistro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegistroActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
                PanelRegistro.setLayout(PanelRegistroLayout);
                PanelRegistroLayout.setHorizontalGroup(
                                PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelRegistroLayout.createSequentialGroup()
                                                                .addContainerGap(25, Short.MAX_VALUE)
                                                                .addGroup(PanelRegistroLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                PanelRegistroLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addGap(24, 24, 24))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                PanelRegistroLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(PanelRegistroLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(btnRegistro,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                86,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                95,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(38, 38, 38)))));
                PanelRegistroLayout.setVerticalGroup(
                                PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelRegistroLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                46, Short.MAX_VALUE)
                                                                .addComponent(btnRegistro)
                                                                .addGap(37, 37, 37)));

                PanelHead.setBackground(new java.awt.Color(219, 213, 195));

                jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 102, 0));
                jLabel1.setText("La vida es bella");

                javax.swing.GroupLayout PanelHeadLayout = new javax.swing.GroupLayout(PanelHead);
                PanelHead.setLayout(PanelHeadLayout);
                PanelHeadLayout.setHorizontalGroup(
                                PanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelHeadLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                205,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                PanelHeadLayout.setVerticalGroup(
                                PanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelHeadLayout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(23, Short.MAX_VALUE)));

                btnIniciarS.setBackground(new java.awt.Color(0, 153, 0));
                btnIniciarS.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                btnIniciarS.setForeground(new java.awt.Color(255, 255, 255));
                btnIniciarS.setText("Iniciar sesion");
                btnIniciarS.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                btnIniciarS.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnIniciarSActionPerformed(evt);
                        }
                });

                lblCorreo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                lblCorreo.setText("Correo");

                TfCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                TfCorreo.setBorder(null);
                TfCorreo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TfCorreoActionPerformed(evt);
                        }
                });
                TfCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                TfCorreoKeyPressed(evt);
                        }
                });

                jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

                limpiarCorreo.setText("x");
                limpiarCorreo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                limpiarCorreoActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PanelHead, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel2)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(PfContra,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                227,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblCorreo,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                76,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jSeparator1)
                                                                                                                .addComponent(TfCorreo,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                239,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(90, 90, 90)
                                                                                                .addComponent(jSeparator2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                227,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(btnIniciarS,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                192,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(45, 45, 45)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(limpiarCorreo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(PanelRegistro,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(14, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(PanelHead,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(49, 49, 49)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblCorreo)
                                                                                                                .addComponent(TfCorreo,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(limpiarCorreo))
                                                                                                .addGap(0, 0, 0)
                                                                                                .addComponent(jSeparator1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                11,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(26, 26, 26)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(PfContra,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(jSeparator2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                11,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(37, 37, 37)
                                                                                                .addComponent(btnIniciarS,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                44,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(PanelRegistro,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(89, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void TfCorreoKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_TfCorreoKeyPressed
                // TODO add your handling code here:
        }// GEN-LAST:event_TfCorreoKeyPressed

        private void PfContraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PfContraActionPerformed
                btnIniciarS.doClick();
        }// GEN-LAST:event_PfContraActionPerformed

        private void limpiarCorreoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limpiarCorreoActionPerformed
                TfCorreo.setText("");
                TfCorreo.requestFocus();
        }// GEN-LAST:event_limpiarCorreoActionPerformed

        private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistroActionPerformed
                // Abrir formulario de registro
                FrmRegistro frmRegistro = new FrmRegistro(this);
                frmRegistro.setVisible(true);
                this.setVisible(false);
        }// GEN-LAST:event_btnRegistroActionPerformed

        private void btnIniciarSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIniciarSActionPerformed
                // Obtener datos del formulario
                String correo = TfCorreo.getText().trim();
                String password = new String(PfContra.getPassword());

                // Validar que no estén vacíos
                if (correo.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Por favor ingrese su correo electrónico",
                                        "Campo requerido",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                        TfCorreo.requestFocus();
                        return;
                }

                // Validar formato de correo electrónico
                if (!correo.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Por favor ingrese un correo electrónico válido (ejemplo: usuario@dominio.com)",
                                        "Correo inválido",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                        TfCorreo.requestFocus();
                        return;
                }

                if (password.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Por favor ingrese su contraseña",
                                        "Campo requerido",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                        PfContra.requestFocus();
                        return;
                }

            try {
                DTOS.UsuarioDTO usuario = controlPresentacion.validarLogin(correo, password);
                if (usuario.getInfoPersonal().getCorreo().equalsIgnoreCase("admin@gmail.com")) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "¡Bienvenido Administrador!",
                            "Acceso Administrativo",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    this.setContentPane(new JPAdmin());
                    this.setTitle("Panel de Administración");
                    this.revalidate();
                    this.repaint();
                    this.pack();
                    this.setLocationRelativeTo(null);
                    return;
                }
     
                        // Establecer el usuario logueado para pre-llenar formularios
                        controlPresentacion.setUsuarioLogueado(usuario);

                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "¡Bienvenido " + usuario.getInfoPersonal().getNombre() + "!",
                                        "Login exitoso",
                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                        controlPresentacion.mostrarMenuPrincipal();
                        this.dispose();

                } catch (Exception e) {
                        PfContra.setText("");
                        PfContra.requestFocus();
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        e.getMessage(),
                                        "Error de inicio de sesión",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                }
        }

        private void TfCorreoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TfCorreoActionPerformed

        }// GEN-LAST:event_TfCorreoActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FrmInicioSesion().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel PanelHead;
        private javax.swing.JPanel PanelRegistro;
        private javax.swing.JPasswordField PfContra;
        private javax.swing.JTextField TfCorreo;
        private javax.swing.JButton btnIniciarS;
        private javax.swing.JButton btnRegistro;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lblCorreo;
        private javax.swing.JButton limpiarCorreo;
        // End of variables declaration//GEN-END:variables
}
