/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import DTOS.SolicitudAdopcionDTO;
import control.ControlPresentacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick
 */
public class JPSolicitudes extends javax.swing.JPanel {

    private ControlPresentacion controlPresentacion;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form JPSolicitudes
     */
    public JPSolicitudes() {
        initComponents();
        configurarTabla();
    }

    public void setControlPresentacion(ControlPresentacion controlPresentacion) {
        this.controlPresentacion = controlPresentacion;
        cargarSolicitudes();
    }

    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[] { "ID", "Mascota", "Fecha Solicitud", "Estado" }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer la tabla de solo lectura
            }
        };
        tablaSolicitudes.setModel(modeloTabla);

        // Ocultar columna ID
        tablaSolicitudes.getColumnModel().getColumn(0).setMinWidth(0);
        tablaSolicitudes.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaSolicitudes.getColumnModel().getColumn(0).setWidth(0);
    }

    private void cargarSolicitudes() {
        if (controlPresentacion == null) {
            System.err.println("DEBUG: ControlPresentacion no está configurado");
            return;
        }

        // Limpiar tabla
        modeloTabla.setRowCount(0);

        try {
            List<SolicitudAdopcionDTO> solicitudes = controlPresentacion.obtenerSolicitudesUsuario();

            if (solicitudes == null || solicitudes.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "No tienes solicitudes de adopción registradas.",
                        "Sin solicitudes",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            for (SolicitudAdopcionDTO solicitud : solicitudes) {
                Object[] fila = new Object[4];
                fila[0] = solicitud.getId(); // ID (oculto)
                String nombreMascota = "N/A";
                if (solicitud.getMascota() != null) {
                    nombreMascota = solicitud.getMascota().getNombre() != null ? solicitud.getMascota().getNombre()
                            : solicitud.getMascota().getId();
                }
                fila[1] = nombreMascota;

                // Formatear fecha de solicitud
                if (solicitud.getFechaSolicitud() != null) {
                    java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter
                            .ofPattern("dd/MM/yyyy HH:mm");
                    fila[2] = solicitud.getFechaSolicitud().format(formatter);
                } else {
                    fila[2] = "N/A";
                }

                fila[3] = solicitud.getEstado() != null ? solicitud.getEstado() : "Pendiente";

                modeloTabla.addRow(fila);
            }

        } catch (Exception e) {
            System.err.println("DEBUG: Excepción en cargarSolicitudes: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar solicitudes: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btncancelarcita = new javax.swing.JButton();
        btneditarcita = new javax.swing.JButton();

        setBackground(new java.awt.Color(219, 213, 195));

        jPanel1.setBackground(new java.awt.Color(219, 213, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tablaSolicitudes = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setViewportView(tablaSolicitudes);
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 900, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("MIS SOLICITUDES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 33, -1, -1));

        btncancelarcita.setText("Cancelar cita");
        btncancelarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        btneditarcita.setText("editar cita");
        btneditarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(btneditarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarcitaActionPerformed(java.awt.event.ActionEvent evt) {
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una solicitud para cancelar su cita.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSolicitud = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas cancelar la cita de esta solicitud?", "Confirmar cancelación de cita",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                controlPresentacion.cancelarCita(idSolicitud);
                cargarSolicitudes();
                JOptionPane.showMessageDialog(this, "Cita cancelada exitosamente.", "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cancelar la cita: " + e.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btneditarcitaActionPerformed(java.awt.event.ActionEvent evt) {
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una solicitud para actualizar su cita.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSolicitud = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

        try {
            controlPresentacion.iniciarReprogramacionCita(idSolicitud);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al iniciar reprogramación: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCancelarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarSolicitudActionPerformed
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor selecciona una solicitud para cancelar.",
                    "Selección requerida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSolicitud = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
        String estado = (String) modeloTabla.getValueAt(filaSeleccionada, 3);

        // Verificar que no esté ya cancelada
        if ("Cancelada".equalsIgnoreCase(estado)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Esta solicitud ya está cancelada.",
                    "Solicitud cancelada",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Confirmar cancelación
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas cancelar esta solicitud de adopción?",
                "Confirmar cancelación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                controlPresentacion.cancelarSolicitudAdopcion(idSolicitud);

                // Actualizar tabla
                cargarSolicitudes();

                JOptionPane.showMessageDialog(
                        this,
                        "Solicitud cancelada exitosamente.",
                        "Cancelación exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Error al cancelar la solicitud: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_btnCancelarSolicitudActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed
        cargarSolicitudes();
    }// GEN-LAST:event_btnActualizarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlPresentacion != null) {
            controlPresentacion.mostrarInfoResumen();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelarcita;
    private javax.swing.JButton btneditarcita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
