/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import DTOS.SolicitudAdopcionDTO;
import control.ControlPresentacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
/**
 * Panel para visualizar y gestionar las solicitudes de adopción del usuario.
 * 
 * @author angel
 */
public class JPSolicitudes extends javax.swing.JPanel {

    private ControlPresentacion controlPresentacion;
    private DefaultTableModel modeloTabla;

    /**
     * Constructor del panel.
     * Configura la tabla y los componentes visuales.
     */
    public JPSolicitudes() {
        initComponents();
        configurarTabla();
    }

    /**
     * Establece el controlador de presentación y carga las solicitudes.
     * 
     * @param controlPresentacion El controlador de presentación.
     */
    public void setControlPresentacion(ControlPresentacion controlPresentacion) {
        this.controlPresentacion = controlPresentacion;
        cargarSolicitudes();
    }

    /**
     * Configura el modelo y las columnas de la tabla.
     */
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[] { "ID", "Mascota", "Fecha Solicitud", "Fecha Cita", "Estado" }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer la tabla de solo lectura
            }
        };
        tablaSolicitudes.setModel(modeloTabla);

        // Ocultar columna ID
        tablaSolicitudes.getColumnModel().getColumn(0).setMinWidth(0);
        tablaSolicitudes.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaSolicitudes.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * Carga las solicitudes del usuario en la tabla.
     */
    private void cargarSolicitudes() {
        if (controlPresentacion == null) {
            System.err.println("DEBUG: ControlPresentacion no está configurado");
            return;
        }

        // Limpiar tabla
        modeloTabla.setRowCount(0);

        try {
            List<SolicitudAdopcionDTO> solicitudes = controlPresentacion.obtenerSolicitudesUsuario();

            if (solicitudes == null || solicitudes.isEmpty()) {
                return;
            }

            for (SolicitudAdopcionDTO solicitud : solicitudes) {
                Object[] fila = new Object[5];
                fila[0] = solicitud.getId(); // ID (oculto)
                String nombreMascota = "N/A";
                if (solicitud.getMascota() != null) {
                    nombreMascota = solicitud.getMascota().getNombre() != null ? solicitud.getMascota().getNombre()
                            : solicitud.getMascota().getId();
                }
                fila[1] = nombreMascota;

                // Formatear fecha de solicitud
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter
                        .ofPattern("dd/MM/yyyy HH:mm");

                if (solicitud.getFechaSolicitud() != null) {
                    fila[2] = solicitud.getFechaSolicitud().format(formatter);
                } else {
                    fila[2] = "N/A";
                }

                // Fecha Cita
                if (solicitud.getFechaCita() != null) {
                    fila[3] = solicitud.getFechaCita().format(formatter);
                } else {
                    fila[3] = "Sin Cita";
                }

                fila[4] = solicitud.getEstado() != null ? solicitud.getEstado() : "Pendiente";

                modeloTabla.addRow(fila);
            }

        } catch (Exception e) {
            System.err.println("DEBUG: Excepción en cargarSolicitudes: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar solicitudes: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncancelarcita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(219, 213, 195));

        jPanel1.setBackground(new java.awt.Color(219, 213, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelarcita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btncancelarcita.setText("Cancelar Cita");
        btncancelarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarcitaActionPerformed(evt);
            }
        });

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(tablaSolicitudes);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("MIS SOLICITUDES");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(490, 490, 490)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(321, 321, 321)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(403, 403, 403)
                                                .addComponent(btncancelarcita, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(352, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(430, 430, 430)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel2)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 430,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(btnActualizar,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncancelarcita, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed
        cargarSolicitudes();

    }// GEN-LAST:event_btnActualizarActionPerformed

    private void btncancelarcitaActionPerformed(java.awt.event.ActionEvent evt) {
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una solicitud para cancelar su cita.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSolicitud = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas cancelar la cita de esta solicitud?", "Confirmar cancelación de cita",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                controlPresentacion.cancelarCita(idSolicitud);
                cargarSolicitudes();
                JOptionPane.showMessageDialog(this, "Cita cancelada exitosamente.", "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cancelar la cita: " + e.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btneditarcitaActionPerformed(java.awt.event.ActionEvent evt) {
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una solicitud para actualizar su cita.",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSolicitud = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

        try {
            controlPresentacion.iniciarReprogramacionCita(idSolicitud);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al iniciar reprogramación: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCancelarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarSolicitudActionPerformed
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor selecciona una solicitud para cancelar.",
                    "Selección requerida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSolicitud = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
        String estado = (String) modeloTabla.getValueAt(filaSeleccionada, 4);

        // Verificar que no esté ya cancelada
        if ("Cancelada".equalsIgnoreCase(estado)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Esta solicitud ya está cancelada.",
                    "Solicitud cancelada",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Confirmar cancelación
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas cancelar esta solicitud de adopción?",
                "Confirmar cancelación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                controlPresentacion.cancelarSolicitudAdopcion(idSolicitud);

                // Actualizar tabla
                cargarSolicitudes();

                JOptionPane.showMessageDialog(
                        this,
                        "Solicitud cancelada exitosamente.",
                        "Cancelación exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Error al cancelar la solicitud: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlPresentacion != null) {
            controlPresentacion.mostrarInfoResumen();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** Botón para actualizar la lista de solicitudes */
    private javax.swing.JButton btnActualizar;
    /** Botón para cancelar la cita */
    private javax.swing.JButton btncancelarcita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    /** Tabla de solicitudes */
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
