/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Erick
 */
public class PetCardPanel extends javax.swing.JPanel {

    private String mascotaId;

    /**
     * Creates new form PetCardPanel
     */
    public PetCardPanel() {
        initComponents();
    }

    /**
     * Establece el nombre de la mascota
     */
    public void setNombreMascota(String nombre) {
        lbNombreMascota.setText(nombre);
    }

    /**
     * Establece la imagen de la mascota
     * Soporta rutas relativas (desde resources) y absolutas
     */
    public void setImagenMascota(String urlImagen) {
        try {
            if (urlImagen != null && !urlImagen.isEmpty()) {
                ImageIcon icon = null;

                // Verificar si es una URL de internet (HTTP/HTTPS)
                if (urlImagen.startsWith("http://") || urlImagen.startsWith("https://")) {
                    try {
                        java.net.URL url = new java.net.URL(urlImagen);
                        icon = new ImageIcon(url);
                    } catch (Exception e) {
                        System.err.println("Error cargando imagen desde URL: " + urlImagen);
                        e.printStackTrace();
                    }
                }
                // Intentar cargar desde resources (ruta relativa que empieza con /)
                else if (urlImagen.startsWith("/")) {
                    java.net.URL imgURL = getClass().getResource(urlImagen);
                    if (imgURL != null) {
                        icon = new ImageIcon(imgURL);
                    } else {
                        System.err.println("No se encontró la imagen en resources: " + urlImagen);
                    }
                }
                // Es una ruta absoluta local
                else {
                    File imgFile = new File(urlImagen);
                    if (imgFile.exists()) {
                        icon = new ImageIcon(urlImagen);
                    } else {
                        System.err.println("No se encontró la imagen en disco: " + urlImagen);
                    }
                }

                // Si se cargó la imagen, redimensionarla y mostrarla
                if (icon != null && icon.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE) {
                    Image img = icon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH);
                    lbImagenMascota.setIcon(new ImageIcon(img));
                    lbImagenMascota.setText("");
                } else {
                    lbImagenMascota.setText("Sin imagen");
                }
            } else {
                lbImagenMascota.setText("Sin imagen");
            }
        } catch (Exception e) {
            lbImagenMascota.setText("Error al cargar");
            System.err.println("Error cargando imagen: " + urlImagen);
            e.printStackTrace();
        }
    }

    /**
     * Establece el ID de la mascota
     */
    public void setMascotaId(String id) {
        this.mascotaId = id;
    }

    /**
     * Obtiene el ID de la mascota
     */
    public String getMascotaId() {
        return mascotaId;
    }

    /**
     * Agrega un listener al botón de detalle
     */
    public void agregarListenerDetalle(ActionListener listener) {
        btn_infoMascota.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbImagenMascota = new javax.swing.JLabel();
        btn_infoMascota = new javax.swing.JButton();
        lbNombreMascota = new javax.swing.JLabel();

        lbImagenMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagenMascota.setText("image");

        btn_infoMascota.setText("VER DETALLES");
        btn_infoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoMascotaActionPerformed(evt);
            }
        });

        lbNombreMascota.setText("nombreMascota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 38, Short.MAX_VALUE)
                                .addComponent(lbImagenMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 285,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbNombreMascota)
                                                        .addGap(179, 179, 179))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(btn_infoMascota, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(139, 139, 139)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbImagenMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lbNombreMascota)
                                .addGap(18, 18, 18)
                                .addComponent(btn_infoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infoMascotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_infoMascotaActionPerformed

    }// GEN-LAST:event_btn_infoMascotaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_infoMascota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImagenMascota;
    private javax.swing.JLabel lbNombreMascota;
    // End of variables declaration//GEN-END:variables
}
